os: linux
services:
   - docker
sudo: required
language: python
env:
  global:
    - CONAN_UPLOAD=1
    - CONAN_USERNAME="jgsogo"
    - CONAN_CHANNEL="ci"
    - CONAN_TOTAL_PAGES=1
    - CONAN_CURRENT_PAGE=1
    - CONAN_PIP_PACKAGE="conan bzr --upgrade"  # When using docker this is how we can install pacakges there

  matrix:
    - CONAN_GCC_VERSIONS=5.4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.3 CONAN_USE_DOCKER=1
matrix:
   include:
       - os: osx
         osx_image: xcode7.3 # apple-clang 6.1
         language: generic
         env:
       - os: osx
         osx_image: xcode8.1
         language: generic
         env:

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh

