
find_path(SQLITE3CC_INCLUDE_DIR NAMES sqlite3cc.h PATHS ${CONAN_INCLUDE_DIRS_SQLITE3CC})
find_library(SQLITE3CC_LIBRARY NAMES ${CONAN_LIBS_SQLITE3CC} PATHS ${CONAN_LIB_DIRS_SQLITE3CC})

IF(CMAKE_SYSTEM_NAME STREQUAL "Linux")
   #SET(EXTRA_LIBS dl pthread)
ENDIF()

set(SQLITE3CC_INCLUDE_DIRS ${SQLITE3CC_INCLUDE_DIR})
set(SQLITE3CC_LIBRARIES ${SQLITE3CC_LIBRARY} ${EXTRA_LIBS})

mark_as_advanced(SQLITE3CC_LIBRARY SQLITE3CC_INCLUDE_DIR)

message("** SQLite3cc found by Conan!")
set(SQLITE3CC_FOUND TRUE)
message("   - libraries:  ${SQLITE3CC_LIBRARIES}")
message("   - includes:  ${SQLITE3CC_INCLUDE_DIRS}")

